### ISSUE TITLE
nonce must be unique for all time, for a given key

### ISSUE THREAD

**Issue by jeremychase** [bregydoc/blackholeDB#1]
https://github.com/bregydoc/blackholeDB/blob/33eb8d346f67ee927fac7b7df39d74635c301a36/singularity.go#L28

From [gcm.Seal() godoc](https://golang.org/pkg/crypto/cipher/#AEAD):
> The nonce must be NonceSize() bytes long and unique for all time, for a given key.

**Comment by n2p5** [comment]
@bregydoc  and @JeremyChase I just made a PR that would prefix nonces with binary encoded unix timestamps to give a 4 byte time series name space in single second resolution to randomly generated nonces.

you can check it out here: https://github.com/bregydoc/blackholeDB/pull/3
